<?php
require_once dirname(__DIR__) . '/src/config.php';
$whatsapp = preg_replace('/\D/', '', setting('whatsapp_number', env('WHATSAPP_NUMBER', '')));
$hero = setting('jaguar_image', 'https://images.unsplash.com/photo-1725397006223-8a10a4c2bc0b?auto=format&fit=crop&q=88&w=2200');
$tours = db()->query("SELECT title FROM tours WHERE active = 1 ORDER BY featured DESC,title")->fetchAll(PDO::FETCH_COLUMN);
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Planeje sua viagem | <?= e(setting('site_name','Pantanal Experience')) ?></title><meta name="description" content="Conte como imagina sua viagem ao Pantanal e receba um atendimento personalizado pelo WhatsApp."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="site-header" data-header><a class="brand" href="index.php"><span>PE</span><b><?= e(setting('site_name','Pantanal Experience')) ?></b></a><button class="menu-toggle" type="button" data-menu-toggle>Menu</button><nav data-menu><a href="index.php#experiencias">Experiências</a><a href="destinos.php">Destinos</a><a href="sobre.php">Sobre nós</a><a href="index.php#faq">FAQ</a><a class="nav-cta" href="contato.php">Planejar viagem</a></nav></header>
<main>
<section class="page-hero" style="background-image:url('<?= e($hero) ?>')"><div class="reveal"><p class="eyebrow">Planeje sua viagem</p><h1>Conte o que você quer viver. Nós desenhamos o caminho.</h1><p>Preencha as informações principais e continue a conversa diretamente pelo WhatsApp.</p></div></section>
<section class="page-section contact-grid">
  <div class="reveal"><p class="eyebrow dark">Atendimento personalizado</p><h2>Seu roteiro começa com uma conversa.</h2><p>Não trabalhamos apenas com datas e número de viajantes. Queremos entender se sua prioridade é fotografia, observação de onça-pintada, família, aventura, conforto, aves ou uma combinação de tudo isso.</p><p>Com essas informações conseguimos sugerir duração, região, hospedagem e experiências mais adequadas para o seu perfil.</p></div>
  <div class="contact-card reveal"><h3>Começar planejamento</h3><form id="general-whatsapp-form" data-whatsapp="<?= e($whatsapp) ?>"><label>Seu nome<input name="name" required></label><label>Experiência de interesse<select name="tour"><option value="Roteiro personalizado">Roteiro personalizado</option><?php foreach($tours as $tour): ?><option value="<?= e($tour) ?>"><?= e($tour) ?></option><?php endforeach; ?></select></label><div class="form-row"><label>Adultos<input type="number" min="1" name="adults" value="2" required></label><label>Crianças<input type="number" min="0" name="children" value="0" required></label></div><div class="form-row"><label>Entrada<input type="date" name="start_date" required></label><label>Saída<input type="date" name="end_date" required></label></div><label>O que não pode faltar?<textarea name="notes" placeholder="Ex.: observar onças, fotografia, passeio de barco, viagem com crianças..."></textarea></label><button class="btn-dark" type="submit">Enviar informações pelo WhatsApp</button></form></div>
</section>
</main>
<footer class="footer-premium"><div><a class="brand footer-brand" href="index.php"><span>PE</span><b><?= e(setting('site_name','Pantanal Experience')) ?></b></a><p>Expedições e experiências cuidadosamente desenhadas no Pantanal de Mato Grosso.</p></div><div><span>Explorar</span><a href="index.php#passeios">Experiências</a><a href="destinos.php">Destinos</a><a href="sobre.php">Sobre nós</a></div><div><span>Atendimento</span><a href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">WhatsApp</a></div></footer><a class="whatsapp-float" href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">WA</a><script src="assets/js/app.js"></script></body></html>