<?php
require_once dirname(__DIR__) . '/src/config.php';
$whatsapp = preg_replace('/\D/', '', setting('whatsapp_number', env('WHATSAPP_NUMBER', '')));
$landscape = setting('transpantaneira_image', 'https://images.unsplash.com/photo-1690989751090-e29411e007b2?auto=format&fit=crop&q=88&w=2200');
$jaguar = setting('porto_jofre_image', 'https://images.unsplash.com/photo-1681227367357-8968aeab739f?auto=format&fit=crop&q=88&w=2000');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Destinos | <?= e(setting('site_name','Pantanal Experience')) ?></title><meta name="description" content="Descubra a Transpantaneira, Porto Jofre e os principais cenários do Pantanal Norte."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="site-header" data-header><a class="brand" href="index.php"><span>PE</span><b><?= e(setting('site_name','Pantanal Experience')) ?></b></a><button class="menu-toggle" type="button" data-menu-toggle>Menu</button><nav data-menu><a href="index.php#experiencias">Experiências</a><a href="destinos.php">Destinos</a><a href="sobre.php">Sobre nós</a><a href="index.php#faq">FAQ</a><a class="nav-cta" href="contato.php">Planejar viagem</a></nav></header>
<main>
<section class="page-hero" style="background-image:url('<?= e($landscape) ?>')"><div class="reveal"><p class="eyebrow">Pantanal Norte</p><h1>Estradas, rios e encontros que só existem aqui.</h1><p>Da Transpantaneira a Porto Jofre, cada trecho da viagem revela um Pantanal diferente.</p></div></section>
<section class="page-section split-section" id="transpantaneira"><img class="reveal" src="<?= e($landscape) ?>" alt="Transpantaneira e paisagem do Pantanal"><div class="reveal"><p class="eyebrow dark">Destino 01</p><h2>Transpantaneira</h2><p>A rodovia Transpantaneira cruza áreas de campos, baías, corixos e pontes de madeira, oferecendo uma sucessão de oportunidades para observar aves, capivaras, jacarés, cervos e outros animais.</p><p>Mais do que um deslocamento até Porto Jofre, a estrada faz parte da própria experiência. Por isso, nossos roteiros reservam tempo para paradas, observação e fotografia ao longo do percurso.</p><a class="btn-dark" href="index.php#passeios">Ver roteiros</a></div></section>
<section class="page-section split-section" id="porto-jofre"><div class="reveal"><p class="eyebrow dark">Destino 02</p><h2>Porto Jofre</h2><p>No final da Transpantaneira, Porto Jofre se torna a base para expedições fluviais pelos rios Cuiabá, Piquiri e São Lourenço. É um dos pontos mais procurados do Pantanal para observação de onças-pintadas em vida livre.</p><p>As saídas de barco acontecem principalmente nas primeiras horas da manhã e no fim da tarde, acompanhando os períodos de maior atividade da fauna.</p><a class="btn-dark" href="index.php#passeios">Explorar expedições</a></div><img class="reveal" src="<?= e($jaguar) ?>" alt="Onça-pintada na região de Porto Jofre"></section>
<section class="page-section"><p class="eyebrow dark">Como combinamos os destinos</p><h2>Uma rota desenhada de ponta a ponta.</h2><div class="facts-strip reveal"><div><strong>01</strong><span>Chegada em Cuiabá e organização do deslocamento.</span></div><div><strong>02</strong><span>Travessia da Transpantaneira com paradas para fauna.</span></div><div><strong>03</strong><span>Hospedagem em pousada ou lodge escolhido para o perfil do grupo.</span></div><div><strong>04</strong><span>Expedições terrestres e fluviais em Porto Jofre.</span></div></div></section>
</main>
<footer class="footer-premium"><div><a class="brand footer-brand" href="index.php"><span>PE</span><b><?= e(setting('site_name','Pantanal Experience')) ?></b></a><p>Expedições e experiências cuidadosamente desenhadas no Pantanal de Mato Grosso.</p></div><div><span>Explorar</span><a href="index.php#passeios">Experiências</a><a href="sobre.php">Sobre nós</a></div><div><span>Atendimento</span><a href="contato.php">Planejar viagem</a><a href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">WhatsApp</a></div></footer><a class="whatsapp-float" href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">WA</a><script src="assets/js/app.js"></script></body></html>