<?php
require_once dirname(__DIR__) . '/src/config.php';
$q = trim($_GET['q'] ?? ''); $category = trim($_GET['category'] ?? '');
$sql='SELECT * FROM tours WHERE active = 1'; $params=[];
if($q!==''){ $sql.=' AND (title LIKE :q OR short_description LIKE :q OR description LIKE :q OR location LIKE :q OR category LIKE :q)'; $params['q']="%{$q}%"; }
if($category!==''){ $sql.=' AND category = :category'; $params['category']=$category; }
$sql.=' ORDER BY featured DESC, created_at DESC'; $stmt=db()->prepare($sql); $stmt->execute($params); $tours=$stmt->fetchAll();
$categories=db()->query("SELECT DISTINCT category FROM tours WHERE active=1 ORDER BY category")->fetchAll(PDO::FETCH_COLUMN);
$heroVideo=setting('hero_video',''); $heroPoster=setting('hero_poster','https://images.unsplash.com/photo-1725397006223-8a10a4c2bc0b?auto=format&fit=crop&q=88&w=2200');
$jaguarImage=setting('jaguar_image',$heroPoster); $landscapeImage=setting('transpantaneira_image','https://images.unsplash.com/photo-1690989751090-e29411e007b2?auto=format&fit=crop&q=88&w=1800');
$jaguarForestImage=setting('porto_jofre_image','https://images.unsplash.com/photo-1681227367357-8968aeab739f?auto=format&fit=crop&q=88&w=1800'); $caimanImage=setting('caiman_image','https://images.unsplash.com/photo-1756724945561-19b48767cd10?auto=format&fit=crop&q=85&w=1800');
$whatsapp=preg_replace('/\D/','',setting('whatsapp_number',env('WHATSAPP_NUMBER',''))); $siteName=setting('site_name','Aruanã Expedições'); $tagline=setting('brand_tagline','O Pantanal não se visita. Se vive.');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($siteName)?> | Expedições exclusivas no Pantanal</title><meta name="description" content="Aruanã Expedições: avistamento de onças, safáris fotográficos e experiências exclusivas no Pantanal, Transpantaneira e Porto Jofre."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="site-header" data-header><a class="brand aruna-brand" href="index.php"><span class="brand-mark">A</span><span class="brand-lockup"><b>ARUANÃ</b><small>EXPEDIÇÕES · PANTANAL</small></span></a><button class="menu-toggle" type="button" data-menu-toggle aria-label="Abrir menu">Menu</button><nav data-menu><a href="#experiencias">Experiências</a><a href="destinos.php">Destinos</a><a href="sobre.php">Sobre nós</a><a href="#galeria">Galeria</a><a href="#faq">FAQ</a><a class="nav-cta" href="https://wa.me/<?=e($whatsapp)?>" target="_blank" rel="noopener">Fale no WhatsApp</a></nav></header>
<main>
<section class="hero hero-premium"><?php if($heroVideo):?><video autoplay muted loop playsinline poster="<?=e($heroPoster)?>"><source src="<?=e($heroVideo)?>"></video><?php else:?><img class="hero-photo" src="<?=e($heroPoster)?>" alt="Onça-pintada no Pantanal"><?php endif;?><div class="hero-shade"></div><div class="hero-noise"></div><div class="hero-content reveal"><p class="eyebrow gold">Expedições exclusivas · Pantanal · Brasil</p><h1><?=e(setting('hero_title','Viva o Pantanal de verdade'))?></h1><p><?=e(setting('hero_subtitle','Expedições exclusivas entre onças, rios e horizontes selvagens. Uma conexão real com a natureza e a vida pantaneira.'))?></p><div class="hero-actions"><a class="btn-gold" href="#passeios">Explorar experiências</a><a class="text-link" href="sobre.php">Conheça a Aruanã →</a></div><form class="hero-search glass" method="get" action="index.php#passeios"><div><label for="q">Encontre sua experiência</label><input id="q" name="q" value="<?=e($q)?>" placeholder="Ex.: onças em Porto Jofre"></div><div><label for="category">Tipo de experiência</label><select id="category" name="category"><option value="">Todas</option><?php foreach($categories as $cat):?><option value="<?=e($cat)?>" <?=$category===$cat?'selected':''?>><?=e($cat)?></option><?php endforeach;?></select></div><button type="submit">Buscar experiências</button></form></div><div class="hero-caption"><?=e($tagline)?></div></section>
<section class="trust-strip"><div><strong>Avistamento de onças</strong><span>Porto Jofre</span></div><div><strong>Guias especialistas</strong><span>Conhecimento local</span></div><div><strong>Expedições 4x4 e barco</strong><span>Segurança e conforto</span></div><div><strong>Fotografia</strong><span>Vida selvagem</span></div><div><strong>Turismo responsável</strong><span>Grupos reduzidos</span></div></section>
<section class="intro premium-intro" id="experiencias"><p class="eyebrow dark">Aruanã Expedições</p><h2><?=e(setting('about_title','Natureza que emociona. Experiências que permanecem.'))?></h2><p><?=e(setting('about_text'))?></p><div class="benefits"><article><span class="benefit-number">01</span><strong>Conhecimento local</strong><span>Guias que leem o território, os rios e os movimentos da fauna.</span></article><article><span class="benefit-number">02</span><strong>Experiência premium</strong><span>Roteiros bem planejados, grupos reduzidos e atenção aos detalhes.</span></article><article><span class="benefit-number">03</span><strong>Turismo responsável</strong><span>Encontros com a natureza sem interferir em seu comportamento.</span></article></div></section>
<section class="jaguar-story"><div class="jaguar-photo reveal"><img src="<?=e($jaguarImage)?>" alt="Onça-pintada no Pantanal"><span>Panthera onca · Pantanal</span></div><div class="story-copy reveal"><p class="eyebrow gold">O grande encontro</p><h2>Em busca da onça-pintada.</h2><p>O Pantanal abriga uma das maiores concentrações de onças-pintadas do planeta. Em Porto Jofre, navegamos pelos rios e corixos acompanhados por guias especializados, respeitando o tempo e o espaço de cada animal.</p><blockquote>“Onde os rios se encontram, a vida selvagem nos ensina o verdadeiro luxo: existir.”</blockquote><a class="btn-gold" href="#passeios">Ver expedições de onça</a></div></section>
<section class="destination-feature"><div class="destination-copy reveal"><p class="eyebrow dark">122 pontes. Um caminho inesquecível.</p><h2>Transpantaneira</h2><p>Mais do que uma estrada, a Transpantaneira é uma travessia pela essência do Pantanal. Jacarés, tuiuiús, capivaras, campos alagados e pores do sol acompanham o caminho até Porto Jofre.</p><a class="text-link dark-link" href="destinos.php">Conhecer o destino →</a></div><img class="reveal" src="<?=e($landscapeImage)?>" alt="Paisagem da Transpantaneira"></section>
<section class="tours-section" id="passeios"><div class="section-title"><div><p class="eyebrow dark">Experiências Aruanã</p><h2>Escolha como viver o Pantanal</h2></div><span><?=count($tours)?> experiência<?=count($tours)===1?'':'s'?></span></div><?php if(!$tours):?><div class="empty">Nenhuma experiência encontrada.</div><?php else:?><div class="tour-grid"><?php foreach($tours as $tour):?><article class="tour-card"><a href="passeio.php?slug=<?=urlencode($tour['slug'])?>" class="tour-image"><img src="<?=e($tour['cover_image']?:$heroPoster)?>" alt="<?=e($tour['title'])?>"><?php if($tour['featured']):?><span class="badge">Seleção Aruanã</span><?php endif;?></a><div class="tour-body"><div class="tour-meta"><span><?=e($tour['category'])?></span><span><?=e($tour['duration'])?></span></div><h3><a href="passeio.php?slug=<?=urlencode($tour['slug'])?>"><?=e($tour['title'])?></a></h3><p><?=e($tour['short_description'])?></p><div class="tour-footer"><div><?php if($tour['price_from']):?><small>a partir de</small><strong>R$ <?=number_format((float)$tour['price_from'],2,',','.')?></strong><?php else:?><strong>Consulte</strong><?php endif;?></div><a href="passeio.php?slug=<?=urlencode($tour['slug'])?>">Explorar →</a></div></div></article><?php endforeach;?></div><?php endif;?></section>
<section class="editorial-gallery" id="galeria"><div class="gallery-heading reveal"><p class="eyebrow">Natureza em estado puro</p><h2>O Pantanal pelos olhos da Aruanã.</h2></div><div class="editorial-grid"><figure class="large reveal"><img src="<?=e($jaguarForestImage)?>" alt="Onça-pintada"><figcaption>Porto Jofre · Onças</figcaption></figure><figure class="reveal"><img src="<?=e($caimanImage)?>" alt="Jacaré no Pantanal"><figcaption>Rios · Vida selvagem</figcaption></figure><figure class="reveal"><img src="<?=e($landscapeImage)?>" alt="Paisagem pantaneira"><figcaption>Transpantaneira · Horizonte</figcaption></figure></div></section>
<section class="testimonials"><p class="eyebrow dark">Memórias de quem viveu</p><h2>O tipo de viagem que fica.</h2><div class="testimonial-grid"><article><div class="stars">★★★★★</div><p>“A sensação foi de estar em um documentário, mas com toda a tranquilidade de uma viagem muito bem organizada.”</p><strong>Marina & Eduardo</strong><span>São Paulo · SP</span></article><article><div class="stars">★★★★★</div><p>“Ver a onça no Rio Cuiabá foi inesquecível. O conhecimento do guia fez toda diferença.”</p><strong>Ricardo M.</strong><span>Curitiba · PR</span></article><article><div class="stars">★★★★★</div><p>“Do primeiro atendimento ao último pôr do sol, tudo foi cuidadoso e personalizado.”</p><strong>Ana Clara</strong><span>Belo Horizonte · MG</span></article></div></section>
<section class="faq-section" id="faq"><div><p class="eyebrow dark">Antes de viajar</p><h2>Perguntas frequentes</h2><p>Seu roteiro também pode ser construído de forma personalizada pela nossa equipe.</p><a class="btn-dark" href="contato.php">Planejar com a Aruanã</a></div><div class="faq-list"><details><summary>Qual a melhor época para ver onças-pintadas?</summary><p>A estação seca costuma favorecer a observação nos rios da região de Porto Jofre. A experiência, porém, muda ao longo de todo o ano.</p></details><details><summary>Os roteiros são privativos?</summary><p>Podemos organizar experiências privativas ou em grupos reduzidos, conforme o pacote escolhido.</p></details><details><summary>Crianças podem participar?</summary><p>Sim. Ajustamos atividades, deslocamentos e duração de acordo com a idade e o perfil da família.</p></details><details><summary>Vocês organizam hospedagem e transporte?</summary><p>Sim. Podemos construir a jornada completa, incluindo hospedagem, transfers e experiências.</p></details></div></section>
<section class="brand-manifesto"><div><span>ARUANÃ</span><p><?=e($tagline)?></p><a href="contato.php">Começar minha expedição</a></div></section>
</main><footer class="footer-premium"><div><a class="brand aruna-brand footer-brand" href="index.php"><span class="brand-mark">A</span><span class="brand-lockup"><b>ARUANÃ</b><small>EXPEDIÇÕES · PANTANAL</small></span></a><p><?=e($tagline)?></p></div><div><span>Explorar</span><a href="#passeios">Experiências</a><a href="destinos.php">Destinos</a><a href="sobre.php">Sobre nós</a></div><div><span>Atendimento</span><a href="contato.php">Planejar viagem</a><a href="https://wa.me/<?=e($whatsapp)?>" target="_blank" rel="noopener">WhatsApp</a></div></footer><a class="whatsapp-float" href="https://wa.me/<?=e($whatsapp)?>" target="_blank" rel="noopener" aria-label="Falar com a Aruanã no WhatsApp">WA</a><script src="assets/js/app.js"></script></body></html>