<?php
require_once dirname(__DIR__) . '/src/config.php';
$whatsapp = preg_replace('/\D/', '', setting('whatsapp_number', env('WHATSAPP_NUMBER', '')));
$hero = setting('jaguar_image', 'https://images.unsplash.com/photo-1725397006223-8a10a4c2bc0b?auto=format&fit=crop&q=88&w=2200');
$landscape = setting('transpantaneira_image', 'https://images.unsplash.com/photo-1690989751090-e29411e007b2?auto=format&fit=crop&q=88&w=1800');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sobre nós | <?= e(setting('site_name','Pantanal Experience')) ?></title><meta name="description" content="Conheça a proposta, os valores e a forma de viajar da Pantanal Experience."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="site-header" data-header><a class="brand" href="index.php"><span>PE</span><b><?= e(setting('site_name','Pantanal Experience')) ?></b></a><button class="menu-toggle" type="button" data-menu-toggle>Menu</button><nav data-menu><a href="index.php#experiencias">Experiências</a><a href="destinos.php">Destinos</a><a href="sobre.php">Sobre nós</a><a href="index.php#faq">FAQ</a><a class="nav-cta" href="contato.php">Planejar viagem</a></nav></header>
<main>
<section class="page-hero" style="background-image:url('<?= e($hero) ?>')"><div class="reveal"><p class="eyebrow">Sobre nós</p><h1>Conhecer o Pantanal é também aprender a respeitá-lo.</h1><p>Desenhamos viagens com conhecimento local, atenção aos detalhes e compromisso com uma experiência responsável.</p></div></section>
<section class="page-section split-section"><div class="reveal"><p class="eyebrow dark">Nossa proposta</p><h2>Viagens pensadas com calma, contexto e propósito.</h2><p><?= e(setting('about_text','Acreditamos que uma grande viagem ao Pantanal não é feita apenas de deslocamentos e passeios. Ela depende da estação, do ritmo da natureza, da experiência dos guias e de uma logística capaz de colocar o viajante no lugar certo, na hora certa.')) ?></p><p>Por isso, cada roteiro é construído de acordo com o perfil do grupo, o tempo disponível e os encontros que o viajante deseja priorizar.</p><a class="btn-dark" href="contato.php">Planejar uma viagem</a></div><img class="reveal" src="<?= e($landscape) ?>" alt="Paisagem do Pantanal"></section>
<section class="page-section"><p class="eyebrow dark">Nossos pilares</p><div class="facts-strip reveal"><div><strong>Local</strong><span>Guias e parceiros que conhecem profundamente o território.</span></div><div><strong>Autoral</strong><span>Roteiros flexíveis, sem formato engessado.</span></div><div><strong>Responsável</strong><span>Observação de fauna sem interferência no comportamento dos animais.</span></div><div><strong>Cuidadoso</strong><span>Logística, hospedagem e deslocamentos pensados em conjunto.</span></div></div></section>
<section class="page-section narrow reveal"><p class="eyebrow dark">O que queremos entregar</p><h2>Uma experiência que continue fazendo sentido depois da viagem.</h2><p>Queremos que cada pessoa volte para casa não apenas com fotografias, mas com uma compreensão maior sobre o Pantanal, seus ciclos de água, sua fauna, suas comunidades e a importância de conservar esse território.</p></section>
</main>
<footer class="footer-premium"><div><a class="brand footer-brand" href="index.php"><span>PE</span><b><?= e(setting('site_name','Pantanal Experience')) ?></b></a><p>Expedições e experiências cuidadosamente desenhadas no Pantanal de Mato Grosso.</p></div><div><span>Explorar</span><a href="index.php#passeios">Experiências</a><a href="destinos.php">Destinos</a></div><div><span>Atendimento</span><a href="contato.php">Planejar viagem</a><a href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">WhatsApp</a></div></footer><a class="whatsapp-float" href="https://wa.me/<?= e($whatsapp) ?>" target="_blank" rel="noopener">WA</a><script src="assets/js/app.js"></script></body></html>