<?php
require_once __DIR__ . '/_auth.php';
require_admin();
$totalTours = (int) db()->query('SELECT COUNT(*) FROM tours')->fetchColumn();
$activeTours = (int) db()->query('SELECT COUNT(*) FROM tours WHERE active = 1')->fetchColumn();
$images = (int) db()->query('SELECT COUNT(*) FROM tour_images')->fetchColumn();
$tours = db()->query('SELECT id,title,location,category,active,featured FROM tours ORDER BY updated_at DESC')->fetchAll();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Admin | Pantanal Experience</title><link rel="stylesheet" href="../assets/css/app.css"></head><body class="admin-shell"><header class="admin-top"><strong>Pantanal Experience · Admin</strong><div><a href="../index.php" target="_blank">Ver site</a> · <a href="logout.php">Sair</a></div></header><main class="admin-main"><div class="admin-actions" style="margin-bottom:24px"><a class="btn" href="passeio-form.php">Novo passeio</a><a class="btn secondary" href="configuracoes.php">Configurações do site</a></div><section class="admin-grid"><article class="admin-card"><span>Passeios cadastrados</span><strong><?= $totalTours ?></strong></article><article class="admin-card"><span>Passeios ativos</span><strong><?= $activeTours ?></strong></article><article class="admin-card"><span>Fotos de passeios</span><strong><?= $images ?></strong></article></section><section class="admin-panel" style="margin-top:24px"><h2>Passeios</h2><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Nome</th><th>Local</th><th>Categoria</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($tours as $tour): ?><tr><td><strong><?= e($tour['title']) ?></strong><?= $tour['featured'] ? ' · Destaque' : '' ?></td><td><?= e($tour['location']) ?></td><td><?= e($tour['category']) ?></td><td><?= $tour['active'] ? 'Ativo' : 'Oculto' ?></td><td><div class="admin-actions"><a class="btn secondary" href="passeio-form.php?id=<?= (int)$tour['id'] ?>">Editar</a><a class="btn secondary" href="galeria.php?tour_id=<?= (int)$tour['id'] ?>">Fotos</a><form method="post" action="passeio-excluir.php" onsubmit="return confirm('Excluir este passeio?')"><input type="hidden" name="id" value="<?= (int)$tour['id'] ?>"><button class="btn danger" type="submit">Excluir</button></form></div></td></tr><?php endforeach; ?></tbody></table></div></section></main></body></html>
